# Generated by Django 5.1.2 on 2024-10-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_worldborder_rename_is_code_country_iso_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldborder',
            old_name='mpoly',
            new_name='geom',
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='fips',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='pop2005',
            field=models.BigIntegerField(verbose_name='Population 2005'),
        ),
    ]
